name: jeve_passmaster_flutter
description: Un portachiavi delle password di JEVE.


publish_to: 'none'


version: 0.2.0+3


environment:
  sdk: ">=2.7.0 <3.0.0"


dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  # Grafica
  cupertino_icons: ^1.0.2
  modal_progress_hud: ^0.1.3

  # Firebase
  firebase_core: ^1.0.2
  firebase_auth: ^1.0.1
  cloud_firestore: ^1.0.3

  # Logica
  provider: ^5.0.0
  rxdart: ^0.26.0

  # Modelli
  json_annotation: ^4.0.1

  # UtilitÃ 
  form_field_validator: ^1.1.0
  random_string: ^2.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  json_serializable: ^4.1.0

  # flutter pub run build_runner build --delete-conflicting-outputs
  build_runner: ^1.12.2


flutter:
  uses-material-design: true


flutter_intl:
  enabled: true
