name: jeve_passmaster_flutter
description: Un portachiavi delle password di JEVE.


publish_to: 'none'


version: 0.0.1+1


environment:
  sdk: ">=2.7.0 <3.0.0"


dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  # Grafica
  cupertino_icons: ^1.0.0
  modal_progress_hud: ^0.1.3

  # Firebase
  firebase_core: ^0.5.2
  firebase_auth: ^0.18.3
  cloud_firestore: ^0.14.3

  # Logica
  provider: ^4.3.2+2
  rxdart: ^0.24.1

  # Modelli
  json_annotation: ^3.1.0

  # UtilitÃ 
  form_field_validator: ^1.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  json_serializable: ^3.5.0

  # flutter pub run build_runner build --delete-conflicting-outputs
  build_runner: ^1.10.4


flutter:
  uses-material-design: true


flutter_intl:
  enabled: true
